export default {

    EXTENSIONS_WILL_LOAD: 'EXTENSIONS_WILL_LOAD',
    EXTENSIONS_DID_LOAD: 'EXTENSIONS_DID_LOAD',
    EXTENSIONS_LOAD: 'EXTENSIONS_LOAD',
    EXTENSIONS_SUCCESS: 'EXTENSIONS_SUCCESS',
    EXTENSION_UNIT_LOAD: 'EXTENSION_UNIT_LOAD',
    EXTENSION_UNIT_SUCCESS: 'EXTENSION_UNIT_SUCCESS',
    EXTENSION_UNIT_DID_LOAD: 'EXTENSION_UNIT_DID_LOAD',
    EXTENSION_UNIT_CORRUPTED: 'EXTENSION_UNIT_CORRUPTED',
    EXTENSIONS_WILL_INVOKE: 'EXTENSIONS_WILL_INVOKE',
    EXTENSIONS_INVOKE: 'EXTENSIONS_INVOKE',
    EXTENSIONS_DID_INVOKE: 'EXTENSIONS_DID_INVOKE'
};
