export default {

    EXTENSIONS_WILL_LOAD: 'EXTENSIONS_WILL_LOAD',
    EXTENSIONS_DID_LOAD: 'EXTENSIONS_DID_LOAD',
    EXTENSIONS_LOAD: 'EXTENSIONS_LOAD',
    EXTENSIONS_SUCCESS: 'EXTENSIONS_SUCCESS',
    SINGLE_EXTENSION_LOAD: 'SINGLE_EXTENSION_LOAD',
    SINGLE_EXTENSION_SUCCESS: 'SINGLE_EXTENSION_SUCCESS',
    SINGLE_EXTENSION_DID_LOAD: 'SINGLE_EXTENSION_DID_LOAD',
    SINGLE_EXTENSION_CORRUPT: 'SINGLE_EXTENSION_CORRUPT',
    EXTENSIONS_WILL_INVOKE: 'EXTENSIONS_WILL_INVOKE',
    EXTENSIONS_INVOKE: 'EXTENSIONS_INVOKE',
    EXTENSIONS_DID_INVOKE: 'EXTENSIONS_DID_INVOKE',
    BORDERLINE_BOOT: '@@all/borderline/BOOT',
    BORDERLINE_READY: '@@all/borderline/READY',
};
