export default {

    SESSION_RECOVER: 'SESSION_RECOVER',
    SESSION_LOGIN: 'SESSION_LOGIN',
    SESSION_LOGIN_SUCCESS: 'SESSION_LOGIN_SUCCESS',
    SESSION_LOGIN_FAILURE: 'SESSION_LOGIN_FAILURE',
    SESSION_LOGOUT: 'SESSION_LOGOUT',
    SESSION_VALID: 'SESSION_VALID'
};
